# Generated by Django 3.2 on 2021-04-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
